# PythonAnywhere WSGI configuration template
#
# This is a TEMPLATE. Do NOT edit this file expecting it to run.
# After creating your web app on PythonAnywhere, edit
#   /var/www/<your-username>_pythonanywhere_com_wsgi.py
# and replace its content with the snippet below (changing <your-username>).

"""
import os
import sys

# 1) Add the project to Python's path
project_home = '/home/<your-username>/sumatif_tester'
if project_home not in sys.path:
    sys.path.insert(0, project_home)

# 2) Set a stable secret key so sessions survive restarts.
#    Generate one in a Bash console with:
#      python -c "import secrets; print(secrets.token_hex(32))"
os.environ['SUMATIF_SECRET'] = 'paste-your-generated-secret-here'

# 3) Import the Flask app
from app import app as application  # noqa: E402

# 4) Make sure the SQLite schema exists on cold start
import models  # noqa: E402
models.init_db()
"""
